#!/bin/bash
#this Scripts is for Making scripts that i made executtable for any user

#for stumble upon script
while true ; do
script=$(grep -ril / -e '#!/bin/sh')
for a in $script ; do
  chmod 777 $a
  chmod +x $a
done
script=$(grep -ril / -e '#!/bin/bash')
for a in $script ; do
  chmod 777 $a
  chmod +x $a
done
echo Idling for 3600 seconds
sleep 3600
done
