#!/bin/bash
echo q7OSx86emu
echo Powered By qemu obviously
export PROGRAMTARGET=$1
export DEBUGFLAGWIN32=$2
arch=$(uname -m)
if [ "$EUID" -ne 0 ]
  then
  echo ${B} Hardware is not accessible
  echo root is not being used or available
  echo Emulation Only Happens On root mode
  exit
fi

echo for launching into Terminal Mode please Run
echo '$ execwin terminal 1'
echo Contactingx86emu
echo Machine Detected Running $arch architechture
sleep 2
bash /module/x86emu/x86.sh
exit
