#!/bin/bash
#sources.shell
HEIGHT=15
WIDTH=80
CHOICE_HEIGHT=18
BACKTITLE="Q7OS File Search"
TITLE="Welcome ${Username}"

OPTIONS=("SearchFile_Generic" "Just search file that have specific content"
"WebConcludeEngine" "Search Information and Compile it using NLTK")


A=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

if [ $A == 'SearchFile_Generic' ]; then
search=$(dialog --title "search" --inputbox "search content or file" 8 40 2>&1 >/dev/tty)
find ${HOME} | grep $search
grep -rnw ${HOME} -e "${search}"
sh /module/QNAengine/externalfilefetcher "${search}" &
exit
fi

if [ $A == 'WebConcludeEngine' ]; then
  sh /module/QNAengine/externalfilefetcher search
  exit
fi
echo Expected exit
exit
