#!/bin/bash
echo q7OS pkgUtils
echo Registering Package to the queue list
#installd is a daemon that Manages all pacman installation From Repositories Syncronization to Auto Update\
#installpkg is a client that requests to installd to install package that can be sourced from Pacman Aur Python Npm
#basically a Unified Package Manager
cd /
updaterepository=0
updatesystem=0
systempackage=/basicpackages
userpackages=/userpackages

echo $1 Package
pacman -Ss $1
npm search $1
pip list $1
exit
