name: q7OS testbuild

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir core; mv * core; cd core ;sudo sh bootloader.sh testbuild
