name: q7OS testbuild

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir /tmp/core; mv * /tmp/core ;cd /tmp/core ;sudo sh bootloader.sh testbuild
